public: true
type: "docs"
category: 
  - "collection development and management" 
  - "reference and outreach"
tags:
  - "policy"
title: "Loan Policies and Procedures"
description: "The policy and procedures for the loan of RAC materials."
pages:
  - ["Loan Policies and Procedures", "index"]
